DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS reading;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE reading (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    site TEXT NOT NULL,
    title TEXT NOT NULL,
    link TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id)
);